language: python
python:
  - 2.6
  - 2.7

services:
  - mysql

install:
  - python setup.py install

before_script:
  - mysql -e 'create database test_hippools;'

script:
  - python setup.py test
  - sudo py.test tests/

notifications:
  email:
    on_success: change
    on_failure: always
